name: Vivliostyle
description: A GitHub action to automate publication builds with Vivliostyle

inputs:
  input:
    description: An input file or location for Vivliostyle CLI
    required: true
    default: '.'
  vivliostyle-version:
    description: A docker image tag of Vivliostyle CLI
    required: true
    default: feat-use-playwright
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        set -e
        docker run --rm -e DEBUG=vs-cli \
          ghcr.io/vivliostyle/cli:${{ inputs.vivliostyle-version }} \
          build ${{ inputs.input }}
