name: Vivliostyle
description: A GitHub action to automate publication builds with Vivliostyle

inputs:
  input:
    description: An input file or location for Vivliostyle CLI
    required: true
    default: '.'
  vivliostyle-version:
    description: A docker image tag of Vivliostyle CLI
    required: true
    default: feat-use-playwright
runs:
  using: node16
  pre: lib/setup/index.js
  main: lib/main/index.js
