on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Vivliostyle action
        uses: ./
        with:
          input: fixtures/wood/index.html
